StaffRoll = {
  tracks = {
    "intro",
    "wait",
    "voxattack0",
    "voxattack1",
    "voxattack2",
    "voxattack3",
    "change",
    "lskmagic0",
    "lskmagic1",
    "lskmagic2",
    "lskmagic3",
    "wait",
    "finish"
  },
  texts = {
    {"", "VOXCHRONICLE Staff", ""},
    {"Produce", "geekdrums", "原案"},
    {"Direction", "TTNTAWASi", "監修、世界観設定"},
    {"Project Management", "giginet", "スケジュール、タスク管理"},
    {"Program", "giginet", "メインプログラム"},
    {"Graphic", "meyco", "アイコン、ゲームUI"},
    {"", "mishima", "ロゴ、メニューUI、ゲームUI"},
    {"", "sugawara", "ゲームUI"},
    {"", "mab", "モンスターデザイン"},
    {"", "TTNTAWASi", "エフェクト・アニメーション"},
    {"", "はこねこ", "ステージ背景"},
    {"", "梅", "ステージ背景"},
    {"", "tobi", "エンディングイラスト"},
    {"Level Design", "hak", "メインステージデザイン"},
    {"", "wildhawk", "レベルデザイン考察"},
    {"", "TTNTAWASi", "メインステージデザイン"},
    {"", "tobi", "チュートリアルデザイン"},
    {"", "giginet", "ボス戦、敵スキルデザイン"},
    {"Music Direction", "Tetu_fs", ""},
    {"Music Compose", "nmb", "チュートリアルステージ"},
    {"", "geekdrums", "1Aシンプルステージ"},
    {"", "rushana", "1B草原ステージ"},
    {"", "shinka_cb", "2A森林ステージ"},
    {"", "yuki_mm", "2B炭鉱ステージ"},
    {"", "Yudaidhun", "2C電脳ステージ"},
    {"", "TTNTAWASi", "3A遺跡ステージ道中"},
    {"", "ハワイ長万部", "3A遺跡ステージボス"},
    {"", "Tetu_fs", "3B古城ステージ道中・ボス"},
    {"", "negiyan", "3C深海ステージ道中"},
    {"", "Ceres78", "3C深海ステージボス"},
    {"", "nmb", "3D宇宙ステージ道中"},
    {"", "AttaQ", "3D宇宙ステージ曲ボス"},
    {"", "Tetu_fs", "メニュー・タイトル・ゲームオーバー"},
    {"", "AttaQ", "エンディングA"},
    {"", "Tetu_fs", "エンディングB"},
    {"", "Yudaidhun", "エンディングC"},
    {"Executive Producer", "geekdrms", ""},
    {"Special Thanks", "All Kawaz Members", ""},
    {"", "2009-2013 Kawaz All rights reserved.", ""},
    {"", "Thank you for your playing", ""},
    {"", "TO BE CONTINUED?", ""},
  }
}

return StaffRoll