StaffRoll = {
  tracks = {
    "intro",
    "wait",
    "wait",
    "voxattack0",
    "voxattack1",
    "voxattack2",
    "voxattack3",
    "tension0",
    "tension1",
    "tension2",
    "tension3",
    "change",
    "lskmagic0",
    "lskmagic1",
    "lskmagic2",
    "lskmagic3",
    "change",
    "finish"
  },
  texts = {
{"", "VOXCHRONICLE Staff", ""},
--stage1
{"Produce", "geekdrums", "原案、監修"},
{"Direction", "TTNTAWASi", "企画、世界観、雑用"},
{"Management", "giginet", "スケジュール、タスク管理、雑用"},
{"Program", "giginet", "メインプログラム"},
{"Level Design", "hak", "ステージデザイン"},
{"Level Design", "giginet", "ボス、敵スキルデザイン"},
{"script", "kataasitobi", "チュートリアルプロット"},
{"", "miio", "スクリプトサポート"},
{"", "TTNTAWASi", "チュートリアル文章、メッセージ"}
{"", "AttaQ", "実績デザイン、文章"},
{"", "wildhawk", "実績、チュートリアルサポート"},
{"Graphic", "meyco", "アイコン、ゲームUI"},
{"", "mishima_", "ロゴ、メニューUI、ゲームUI"},
{"", "mab", "モンスターデザイン"},
--stage2
{"", "TTNTAWASi", "エフェクト・コマンド・ロゴ"},
{"", "sugawara", "ステージ背景"},
{"", "negiyan", "文字"},
{"", "はこねこ", "ステージ背景、文字、ゲームUI"},
{"", "うめ", "ステージ背景"},
{"", "kataasitobi", "エンディングイラスト"},
{"Sound Effect", "nmb", "効果音全般"},
{"Music Direction", "Tetu_fs", "音楽システム監修"},
{"Music Compose", "nmb", "チュートリアルステージ"},
{"", "geekdrums", "1A　荒野ステージ"},
{"", "るしゃな", "1B　平原ステージ"},
{"", "shinka_cb", "2A　森林ステージ"},
{"", "yuki_mm", "2B　炭鉱ステージ"},
{"", "Yudaidhun", "2C　電脳ステージ"},
--stage3
{"", "TTNTAWASi", "3A　遺跡ステージ道中"},
{"", "ハワイ長万部", "3A　遺跡ステージボス"},
{"", "Tetu_fs", "3B　古城ステージ道中・ボス"},
{"", "negiyan", "3C　深海ステージ道中"},
{"", "Ceres78", "3C　深海ステージボス"},
{"", "nmb", "3D　宙域ステージ道中"},
{"", "AttaQ", "3D　宙域ステージ曲ボス"},
{"", "Tetu_fs", "メニュー・タイトル・ゲームオーバー、図鑑"},
{"", "nmb", "エンディングA"},
{"", "Tetu_fs", "エンディングB"},
{"", "Yudaidhun", "エンディングC"},
{"", "AttaQ", "エンディングD"},
{"debag play", "wildhawk", "プレイヤー代表、提言"},
{"Special Thanks", "All Kawaz Members", ""},
    -- 3面アウトロ
{"Executive Producer", "geekdrums", ""},
{" ", "Created by Kawaz", "2009-2013 Kawaz All rights reserved."},
{"", "Thank you for your playing", ""},
{"", "The End", ""},

  }
}

return StaffRoll