git rm Original/skin-hd/cave.zwd
git rm Original/skin-hd/cave_default.plist
git rm Original/skin-hd/cave_default.png
git rm Original/skin-hd/cave_frame_lsk_left.png
git rm Original/skin-hd/cave_frame_lsk_right.png
git rm Original/skin-hd/cave_frame_vox_left.png
git rm Original/skin-hd/cave_frame_vox_right.png
git rm Original/skin-hd/cave_gauge.png
git rm Original/skin-hd/cave_gauge_bg.png
git rm Original/skin-hd/cave_ground.zwd
git rm Original/skin-hd/cave_ground0.png
git rm Original/skin-hd/cave_ground1.png
git rm Original/skin-hd/cave_ground2.png
git rm Original/skin-hd/cave_ground3.png
git rm Original/skin-hd/cave_hp.png
git rm Original/skin-hd/cave_hp_numbers.png
git rm Original/skin-hd/cave_level.png
git rm Original/skin-hd/cave_level_back.png
git rm Original/skin-hd/cave_level_numbers.png
git rm Original/skin-hd/cave_mp.png
git rm Original/skin-hd/cave_mp_off.png
git rm Original/skin-hd/cave_mp_on.png
git rm Original/skin-hd/cave_slash.png
git rm Original/skin-hd/cave_trigger_lsk.png
git rm Original/skin-hd/cave_trigger_on.png
git rm Original/skin-hd/cave_trigger_vox.png
git rm Original/skin-hd/cyber.zwd
git rm Original/skin-hd/cyber_default.pvr.ccz
git rm Original/skin-hd/cyber_gauge.png
git rm Original/skin-hd/cyber_gauge_bg.png
git rm Original/skin-hd/cyber_ground.zwd
git rm Original/skin-hd/cyber_ground0.png
git rm Original/skin-hd/cyber_ground1.png
git rm Original/skin-hd/cyber_ground2.png
git rm Original/skin-hd/cyber_ground3.png
git rm Original/skin-hd/cyber_ground_default.pvr.ccz
git rm Original/skin-hd/cyber_hp.png
git rm Original/skin-hd/cyber_hp_numbers.png
git rm Original/skin-hd/cyber_level.png
git rm Original/skin-hd/cyber_level_numbers.png
git rm Original/skin-hd/cyber_mp.png
git rm Original/skin-hd/cyber_mp_off.png
git rm Original/skin-hd/cyber_mp_on.png
git rm Original/skin-hd/cyber_slash.png
git rm Original/skin-hd/cyber_trigger_lsk.png
git rm Original/skin-hd/cyber_trigger_off.png
git rm Original/skin-hd/cyber_trigger_on.png
git rm Original/skin-hd/cyber_trigger_vox.png
git rm Original/skin-hd/grass.zwd
git rm Original/skin-hd/grass_background.png
