#!/bin/sh
PROJECTNAME=VOXCHRONICLE
GLUEPATH=../Classes/Lua/
GLUENAME=LuaBind
PACKAGENAME=VOXCHRONICLE.pkg
./tolua++ -n $PROJECTNAME -o ${GLUEPATH}${GLUENAME}.cpp -H ../Classes/includes/${GLUENAME}.h $PACKAGENAME
